### ISSUE TITLE
kssh search on all my account, not in the directory path context

### ISSUE THREAD

**Issue by clarsonneur** [forj-oss/kssh#3]
kssh current uses :
`find /home/myAccount/ -name srv_tmpl.yml` 

This is too heavy for large home dir.

On the other side, the idea was more on where you are in the current directory, try to find out if we find that srv_tmpl.yml and not all.

Ex:
```bash
$ cd /home/myaccount/src/myproject/subdir1/subdir2 
$ pwd
/home/myaccount/src/myproject/subdir1/subdir2
$ kssh --details
```
in this example, kssh will search for srv_tmpl.yml in the following order:
1. /home/myaccount/src/myproject/subdir1/subdir2/srv_tmpl.yml ?
2. /home/myaccount/src/myproject/subdir1/srv_tmpl.yml ?
3. /home/myaccount/src/myproject/srv_tmpl.yml ?
4. /home/myaccount/src/srv_tmpl.yml ?
5. /home/myaccount/srv_tmpl.yml ?
6. /home/srv_tmpl.yml ?
7. /srv_tmpl.yml ?

first found, first read.

We can imagine, if we are in git repo:
```bash
$ cd /home/myaccount/src/myproject/subdir1/subdir2 
$ pwd
/home/myaccount/src/myproject/subdir1/subdir2
$ git rev-parse  --show-toplevel
/home/myaccount/src/myproject
$ kssh --details
```
in this example, kssh will search for srv_tmpl.yml in the following order:
1. /home/myaccount/src/myproject/subdir1/subdir2/srv_tmpl.yml ?
2. /home/myaccount/src/myproject/subdir1/srv_tmpl.yml ?
3. /home/myaccount/src/myproject/srv_tmpl.yml ?

first found, first read.

**Comment by cppmx** [comment]
I understand the problem, I didn't consider disk drives too full. Yes, the **find** command will become very slow when a directory contains too many files.

An option to do it with the **find** command would be:
- Get the directory in which we are located: `CurrentDir=$(pwd)`
- Search in that directory the srv_tmpl.yml file: `find $CurrentDir -maxdepth 1 -name srv_tmpl.yml`
- If file is present, then stop the search
- If file is not present, then move back one level: `CurrentDir=$(dirname $CurrentDir)`
- Repeat the search

Another option could be for the **KSSH** command to keep a record of the location of the directory where you imported the data from. For example:
~ / .kssh_import_dirs

And within that file keep a variable for each GIT directory, something like this:
```YAML
---
directories:
  - /home/user/Git/repo1
  - /home/user/Git/repo2
```

In this way, when the **KSSH** command is executed, it will be enough to check if the current directory is inside any of the listed directories.

I'm going to do tests to see which of these two options is more effective.

**Comment by cppmx** [comment]
After doing a couple of tests I have noticed that although the second option is faster, the first option is simpler. In addition, the second option is prone to errors if the user decides to rename the directory without notifying **KSSH**.

So I will proceed with the implementation of the first option.

**Comment by clarsonneur** [comment]
Yes, I agree with you related to the 2nd option.

On the first one, rather then using find, I would use `if [[ -f $CurrentDir/srv_tmpl.yml ]]`

Even with `-maxdepth 1` find is slow compare to a simple file test existence.

Your thought?

**Comment by cppmx** [comment]
You're right, we're not looking for many files, just one.

Your choice is better than using the find command.
